### ISSUE TITLE
First put into the shared memory is slower than subsequent one

### ISSUE THREAD

**Issue by YarShev** [modin-project/unidist#367]
```python
import unidist
import numpy as np
import time

unidist.init()

t0 = time.time()
data = unidist.put(np.arange(10))
t1 = time.time()
print(f"time is {t1 - t0}")

t0 = time.time()
data2 = unidist.put(np.arange(10))
t1 = time.time()
print(f"time is {t1 - t0}")

# time is 2.5319178104400635
# time is 0.06026887893676758
```

Most of the time is spent in https://github.com/modin-project/unidist/blob/fea4507b2bd29ca209f1778de1cb8347de9ee804/unidist/core/backends/mpi/core/communication.py#L981

**Comment by arunjose696** [comment]
The root cause of this issue is  the monitor process has to allocate the shared_memory even before the monitor loop has to start. In the given example (with times 2.53 and 0.06) almost 2.5 seconds is  spend in  _allocate_shared_memory() function for the monitor process. Once the allocation is complete after say 2.5 seconds (taking the example in first comment) the monitor loop becomes ready to receive unidist operations. Once the monitor loop is up and running all the  further puts with similar objects would take similar times.

 The initial allocation of shared memory is not time taking but in _allocate_shared_memory(self): function we [are setting -1 to the service buffer because 0 is a valid value](https://github.com/modin-project/unidist/blob/master/unidist/core/backends/mpi/core/shared_object_store.py#L191-L195). This line is the time consuming operation. I tried removing this [line ](https://github.com/modin-project/unidist/blob/master/unidist/core/backends/mpi/core/shared_object_store.py#L192) from unidist source and could see the time taken for the first put would decrease. 

Have to figure out if there is a faster way to set the service buffer to all -1, or if this could be removed if this is not necessary.
